export const homeDefaults = {
  hero: {
    kicker: 'Northern Warrior',
    heading: 'Train Hard. Build Community.',
    subtext: 'Cumbria\'s premier functional fitness facility.',
    video_url: '/hero-video.mp4',
    image_url: '/feature-1.jpg',
  },
  trust_bar: {
    items: [
      'HYROX Affiliate',
      'HWPO Partner',
      '150+ Members',
      'Est. 2015',
      'Huge Facility',
      'Cumbria\'s Best Gym',
      'Community Driven',
      'Functional Fitness',
    ],
  },
  programs: {
    items: [
      {
        title: 'Class',
        type: 'Daily WOD',
        desc: '7 expertly programmed workouts per week, each 60 minutes. Warm-up, two-part workout and optional homework. Progressive cycles build strength, power, endurance and overall physical preparedness.',
        detail: '7 sessions/week \u00b7 60 min',
        image_url: '/feature-1.jpg',
        image_position: '',
        link: '/start-here',
      },
      {
        title: 'HYROX\u00ae',
        type: 'Race Prep',
        desc: 'Scalable, aerobic-based training building stamina, grit and real-world work capacity. Machine work, sled pushes, running intervals and functional movements.',
        detail: 'Mon \u00b7 Wed \u00b7 Sun',
        image_url: '/feature-2.jpg',
        image_position: '',
        link: '/hyrox',
      },
      {
        title: 'Bodybuilding',
        type: 'Hypertrophy',
        desc: '5 weekly sessions of 60\u201390 minutes combining traditional bodybuilding with functional strength. Focused on aesthetics, quality movement and physique goals.',
        detail: '5 sessions/week \u00b7 60\u201390 min',
        image_url: '/ig/7.png',
        image_position: '',
        link: '/start-here',
      },
      {
        title: 'Weightlifting',
        type: 'Olympic',
        desc: 'Snatch and clean & jerk broken down properly. Positional drills, technique cycles and heavy singles using dedicated 8-week progressive cycles.',
        detail: '8-week cycles \u00b7 All levels',
        image_url: '/ig/10.png',
        image_position: '',
        link: '/start-here',
      },
      {
        title: 'Gymnastics',
        type: 'Skill',
        desc: '8-week cycles dedicated to specific modalities \u2014 from foundational pulling and pressing strength through to muscle-ups and handstand walks.',
        detail: '8-week cycles \u00b7 Skill progressions',
        image_url: '/ig/2.png',
        image_position: '',
        link: '/start-here',
      },
      {
        title: 'EMOM40',
        type: 'Engine Builder',
        desc: 'A staple in Mat Fraser\'s training. Aerobic conditioning with functional movements in a focused 40-minute format \u2014 programmed twice weekly.',
        detail: 'Twice weekly \u00b7 40 min',
        image_url: '/ig/4.png',
        image_position: '',
        link: '/start-here',
      },
      {
        title: 'Kids & Teens',
        type: 'Ages 3\u201318',
        desc: 'Mini Warriors (3\u20135), Little Warriors (5\u201310) and Teen Warriors (10\u201318). Coached, safe and seriously fun \u2014 building confidence, coordination and long-term athletic development.',
        detail: 'Ages 3\u201318 \u00b7 Sunday sessions only',
        image_url: '/feature-3.jpg',
        image_position: '',
        link: '/kids-teens',
      },
    ],
  },
  stats: {
    items: [
      { value: '150', suffix: '+', label: 'Members', sub: 'and growing' },
      { value: '2', suffix: ' Week', label: 'Free Trial', sub: 'no commitment needed' },
      { value: '0', suffix: '', label: 'Contracts', sub: 'ever. train on your terms' },
      { value: '100', suffix: '%', label: 'Community', sub: 'every single session' },
    ],
  },
  testimonials: {
    items: [
      {
        quote: 'Northern Warrior completely changed my approach to fitness. The community here is like nothing else \u2014 everyone pushes you to be better, every single session.',
        name: 'Sarah M.',
        role: 'Member since 2021',
      },
      {
        quote: "I came in knowing nothing about functional fitness. Within 3 months I'd completed my first HYROX race. The coaching is phenomenal.",
        name: 'James T.',
        role: 'HYROX Competitor',
      },
      {
        quote: 'The facility is incredible and the programming is elite. HWPO + great coaches = results. My strength has gone through the roof.',
        name: 'Lauren K.',
        role: 'Unlimited Member',
      },
    ],
  },
  icon_row: {
    heading: 'More than a gym.',
    subtext: 'Every session coached. Every member supported. World-class programming, an in-house physio, and a community that actually shows up for each other.',
    items: [
      { label: 'In-house Physio', desc: 'Support, rehab and return-to-training.' },
      { label: 'Personal Training', desc: '1:1 coaching and bespoke programming.' },
      { label: 'Elite Coaching', desc: 'Structured sessions. Real intent. Real standards.' },
      { label: 'Premium Facility', desc: '500m\u00b2 space built for strength + conditioning.' },
    ],
  },
  scroll_story: {
    items: [
      {
        kicker: 'Functional Fitness',
        heading: 'Grassroots strength. Coached by people who live it.',
        body: 'The foundation of Northern Warrior. Functional Fitness sessions built on movement quality, effort, and community \u2014 coached for all levels.',
        image_url: '/feature-1.jpg',
        image_position: '',
      },
      {
        kicker: 'HYROX',
        heading: 'Built for the race. Trained for the grind.',
        body: 'Hybrid race prep: running, stations, pacing and conditioning \u2014 coached from first-timer to podium finisher.',
        image_url: '/feature-2.jpg',
        image_position: '',
      },
      {
        kicker: 'Kids & Teens',
        heading: 'Building the next generation of athletes.',
        body: 'Mini, Little & Teen Warriors. Confidence, coordination and long-term athletic development \u2014 coached, safe, and seriously fun.',
        image_url: '/feature-3.jpg',
        image_position: '',
      },
    ],
  },
  induction: {
    heading: 'Master the basics \u2014 then build fast.',
    subtext: 'Our induction is designed to teach essential movements and techniques in a supportive, structured environment \u2014 giving you the foundation used across classes at Northern Warrior.',
    items: [
      { title: 'Coached foundations', desc: 'Movement quality, breathing, pacing and confidence.' },
      { title: 'Scalable approach', desc: 'Start safely. Progress consistently.' },
      { title: 'Clear next step', desc: "You'll know exactly which sessions to attend next." },
    ],
  },
  social_carousel: {
    heading: 'Follow the journey.',
    subtext: 'Tag us @northernwarrior and you might end up on our feed.',
  },
}
