export const physioDefaults = {
  hero: {
    kicker: 'In-house Physiotherapy',
    heading: 'Advanced Physio',
    subtext: 'Expert physiotherapy by Marek Emilianowicz \u2014 19+ years of clinical experience, MSc Physiotherapy. Exclusively at Northern Warrior.',
    image_url: '/feature-1.jpg',
  },
  about: {
    kicker: 'Meet Your Physio',
    heading: 'Marek Emilianowicz',
    subheading: 'MSc Physiotherapy \u2014 19+ years experience',
    body: 'With over 19 years of clinical experience and a Master\'s degree in Physiotherapy, Marek brings an evidence-based, hands-on approach to injury treatment and rehabilitation. Incorporating advanced techniques such as manual therapy, dry needling, and Kinesio taping, he provides tailored care to keep you pain-free and performing at your best. Based in-house at Northern Warrior, he works closely with coaches and athletes to ensure you stay strong, recover faster, and train without limits.',
    image_url: '',
    image_position: '50% 30%',
  },
  techniques: {
    heading: 'Treatment Techniques',
    subtext: 'A comprehensive toolkit for diagnosis, treatment and recovery.',
    items: [
      { title: 'Manual Therapy', desc: 'Hands-on joint mobilisation and soft tissue techniques to restore range of motion and reduce pain.', image_url: '', image_position: '' },
      { title: 'Dry Needling', desc: 'Targeted trigger point therapy using fine needles to release deep muscle tension and accelerate recovery.', image_url: '', image_position: '' },
      { title: 'Kinesio Taping', desc: 'Therapeutic taping to support joints, reduce swelling and enhance proprioceptive feedback during training.', image_url: '', image_position: '' },
      { title: 'Sports Massage', desc: 'Deep tissue and sports-specific massage to improve circulation, break down adhesions and speed up recovery.', image_url: '', image_position: '' },
      { title: 'TENS Therapy', desc: 'Transcutaneous electrical nerve stimulation for effective pain management and muscle activation.', image_url: '', image_position: '' },
    ],
  },
  specialisations: {
    heading: 'Areas of Expertise',
    subtext: 'Specialist treatment across a wide range of musculoskeletal conditions.',
    items: [
      { title: 'Sports Injuries', desc: 'From acute sprains and strains to chronic overuse injuries \u2014 diagnosis, treatment and return-to-sport planning.', image_url: '', image_position: '' },
      { title: 'Joint Pain', desc: 'Assessment and treatment of shoulder, knee, hip, ankle and spinal joint pain using manual therapy and exercise prescription.', image_url: '', image_position: '' },
      { title: 'Post-Surgery Rehabilitation', desc: 'Structured rehabilitation programmes following ACL reconstruction, Achilles tendon repair, hip and knee replacements.', image_url: '', image_position: '' },
      { title: 'Performance Optimisation', desc: 'Prehabilitation, movement screening and targeted treatment to push you beyond your limits.', image_url: '', image_position: '' },
    ],
  },
  case_studies: {
    heading: 'Recovery Stories',
    subtext: 'Real results from real athletes.',
    items: [
      {
        kicker: 'Case Study',
        heading: 'Back to Running in 6 Weeks',
        body: 'A Northern Warrior athlete came in with chronic knee pain that had kept them sidelined for months. Through manual therapy, dry needling and a supervised return-to-running programme, they were back in class within 6 weeks \u2014 stronger and pain-free.',
        video_url_1: '',
        video_url_2: '',
        video_url_3: '',
        image_url: '',
      },
      {
        kicker: 'Case Study',
        heading: 'Post-Surgery Shoulder Rehab',
        body: 'Following shoulder surgery, this athlete worked with Marek over 12 weeks to rebuild strength and mobility. A combination of manual therapy, progressive loading and movement coaching got them back to overhead lifts with full confidence.',
        video_url_1: '',
        video_url_2: '',
        image_url: '',
      },
    ],
  },
  member_discount: {
    kicker: 'NW Members',
    heading: 'Exclusive member discount.',
    subtext: 'Northern Warrior members receive a discount on all physiotherapy treatments. Book through the link below or ask at the front desk.',
  },
  testimonials: {
    items: [
      { quote: 'I went to see Marek with an injury I\'d gotten while running. Marek was brilliant in checking all possible causes of the injury, until it was identified. I was then given exercises and advice on what to do to help in my recovery. The movements helped a tremendous amount. After a couple of weeks I was feeling much better \u2014 the care Marek gave and attention to my recovery was brilliant. I really recommend Marek.', name: 'George Cowen', role: 'NW Coach | Athlete' },
      { quote: 'Marek was very professional and made a thorough initial examination to discover the root cause of my back & hip pain. He devised a plan of treatment that has led to the pain being resolved and has given me a better range of movement than I had before! I have recommended him to friends and family for when they need a physio.', name: 'Jackie Fox' },
      { quote: 'Big thanks to Marek for all his work on my long standing shoulder issues which, following a range of manipulation, dry needling and rehabilitation programme has resulted in a pain free, much improved range of motion.', name: 'Mark Neal' },
      { quote: 'Visited Marek couple of weeks ago. I was impressed with the thorough examination and his expertise on the physiotherapy. Recommend 100%.', name: 'Antonis Katsikadamos' },
      { quote: 'Marek has recently helped me with some long term issues. He was very helpful and knowledgeable with diagnosing what was wrong. I also received a detailed follow up plan to help keep the injuries away. I would recommend Marek to anyone!', name: 'Zoe Bradley' },
      { quote: 'I needed help for a back injury. I scheduled an appointment using Marek\'s easy online booking system. Marek was thorough in his assessment, also looking into my other back issues, to benefit me beyond the specific injury I had. After the appointment, I received a personalised exercise routine to help me remember what to work on. I would recommend Marek to anyone seeking physiotherapy support.', name: 'Alex McCarthy' },
      { quote: 'I would like to thank Marek for his professionalism treating a problem of my back recently. I am really grateful for all the advice and treatment he gave me. He has worked wonders!', name: 'Maureen Cromwell' },
      { quote: 'Marek recently supported me in overcoming a knee issue, which I later understood to be bursitis. I found Marek very engaging and knowledgeable. He provided information continually during my treatment plan and explained how the in-person physio sessions and the home exercises would recover my range of motion. I would recommend Marek to anyone requiring the support of a professional physiotherapist.', name: 'John Murphy' },
      { quote: 'I have recently seen Marek with long term lower back, hip and groin issues. He gave a thorough examination before providing physical treatment as well as an easy to follow tailored exercise programme which was concise and easy to fit into a busy life. I also seen Marek for a sports massage which was one of the best I\'ve had out of many. Marek also follows up after appointments to check on progress which is a nice touch.', name: 'Lloyd O\'Neil' },
      { quote: 'Marek was very professional and thorough in his approach. Not only did he treat an ongoing problem but he gave further advice for ongoing prevention.', name: 'Stephen McCourt' },
      { quote: 'I recently saw Marek for a sports massage, targeting my back. Not only did he provide a thorough and invigorating massage, but his personalized attention stood out. He took the time to ask about any specific concerns, and provided valuable advice for addressing them in training. Marek\'s expertise and genuine care for my well-being made for a fantastic experience. I highly recommend him!', name: 'Cindy Schmidt' },
      { quote: 'I am a 74 year old lady who tore her meniscus cartilage. Marek was recommended to me when I was concerned about how to progress forward. I have always found him to be professional, knowledgeable, reassuring and patient and he always involved me in the planning of my exercise routine. I noticed improvement after each home visit and now I see a marked improvement and I feel confident going forward with my future exercise plan. I would highly recommend him to anyone in need of his expertise.', name: 'Monica Reid' },
    ],
  },
  physio_contact: {
    heading: 'Book an Appointment',
    subtext: 'Get in touch with Advanced Physio directly \u2014 or book online.',
    booking_url: 'https://advancedphysiobyemilianowicz.as.me/schedule/b844fe3a',
    whatsapp: '+447503497554',
    email: 'advanced.physiome@gmail.com',
    instagram: 'advanced_physiome',
  },
}
